package model

enum class ConstantStrings(val message: String) {
    SIGNUP("Sign Up"),
    USERNAME("userName"),
    PASSWORD("password"),
    ADDRESS("address"),
    DATEOFBIRTH("dateOfBirth"),
    GENDER("gender"),
    LOGIN("Log In"),
    USERID("userId"),
    DUMMY(""),
    A("A"),
    C("C"),
    PASSWORDCHANGE("Password Change"),
    ADDSTATION("Add Station"),
    TRAINADDITION("Train Addition"),
    STATIONNAME("stationName"),
    CITY("city"),
    DISTANCEFROMCAPECOMORIN("distanceFromCapeComorin"),
    COACHNAME("coachName"),
    NUMBEROFCOMPARTMENTS("noOfCompartments"),
    TOTALSEATSINCOACH("totalSeatsInCoach"),
    FAREPERKM("farePerKm"),
    AVAILABLETICKETSINCOACH("availableTicketsInCoach"),
    TICKETBOOKING("Ticket Booking"),
    STARTINGSTATIONNAME("startingStationName"),
    DESTINATIONSTATIONNAME("destinationStationName"),
    STARTINGSTATIONID("startingStationId"),
    DESTINATIONSTATIONID("destinationStationId"),
    PASSENGERNAME("passengerName"),
    PASSENGERAGE("passengerAge"),
    SLEEPER( "SL"),
    SEATER("SE"),
    AC("AC"),
    ENTERVALIDINPUT("Enter Valid Input")
}